### ISSUE TITLE
What is "Flickbean"?

### ISSUE THREAD

**Issue by J-Cake** [leonli96/flickbean#4]
I somehow (who knows how) came across this repo, and it immediately caught my attention, but as no README or description are provided, I'm not exactly sure what this project fulfills. If anyone could inform me what this program does, that would be greatly appreciated.

Sincerely.

**Comment by lazorfuzz** [comment]
@J-Cake This program was an ill-fated, ill-conceived attempt at building an online coffee bean store. Could I ask why it caught your attention?

Thanks

**Comment by J-Cake** [comment]
@lazorfuzz Hi lazorfuzz, thanks for the rapid reply. If I'm going to tell the truth, there's no real reason except the name that caught my attention. I began to read over the code and soon realised it was a website. 

Thanks for the reply.

**Comment by J-Cake** [comment]
@lazorfuzz Hi lazorfuzz, thanks for the rapid reply. If I'm going to tell the truth, there's no real reason except the name that caught my attention. I began to read over the code and soon realised it was a website. 

Thanks for the reply.
